name: php-laravel-runner
services:
  app:
    image: leopersan/php-laravel-runner:latest
    container_name: php-laravel-runner
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - GIT_REPOSITORY_URL=
      - GIT_BRANCH=main
      - GITHUB_TOKEN=
      - DOCUMENT_ROOT=public
      - INSTALL_CMD=composer install --no-interaction --prefer-dist --optimize-autoloader
      - BUILD_CMD=
      - APP_PORT=80
      - PORT=80
    ports:
      - "80:80"
    volumes:
      - php_laravel_runner_data:/var/www/html

volumes:
  php_laravel_runner_data:

x-casaos:
  id: com.leopersan.php-laravel-runner
  architectures:
    - amd64
    - arm64
    - arm
  main: app
  description:
    en_us: "Deploy contínuo e execução otimizada de aplicações PHP 8.4, Laravel, Symfony e WordPress com Composer, Apache e extensões essenciais."
    pt_br: "Deploy contínuo e execução otimizada de aplicações PHP 8.4, Laravel, Symfony e WordPress com Composer, Apache e extensões essenciais."
  tagline:
    en_us: "PHP 8.4 & Laravel Runner Runner"
    pt_br: "PHP 8.4 & Laravel Runner Runner"
  developer: "Private Market Admin"
  author: "Private Market Admin"
  icon: "https://raw.githubusercontent.com/LeoPersan/cosmos-custom-marketplace/main/Apps/com.leopersan.php-laravel-runner/icon.png"
  thumbnail: "https://raw.githubusercontent.com/LeoPersan/cosmos-custom-marketplace/main/Apps/com.leopersan.php-laravel-runner/icon.png"
  title:
    en_us: "PHP 8.4 & Laravel Runner"
    pt_br: "PHP 8.4 & Laravel Runner"
  category: "Development"
  port_map: "80"
  index: "/"
